---
title: "test_initial"
author: "Anh Mai Bui"
date: "December 3, 2018"
output: pdf_document
---

```{r}
#Create 
install.packages("Ryacas")
install.packages("Deriv")
install.packages("distr")
install.packages("truncnorm")
library(truncnorm)
library(Ryacas)
library(Deriv)
#library(distr)

#######################################
#User supplied parameters

#User supplied g-function
g <- function(x){
  sigma <- 1
  mu <- 0
  val <- 3/sqrt(2*pi*sigma^2)*exp(-(x-mu)^2/(2*sigma^2))
}

#Examples for function g
g(0)
g(1)
g(-1)

#Number of starting points
k_start=2 

#Bounds for x
x.Bound=c(-Inf,Inf) 


#######################################
#Test default deriv() function + Simplify() function
sigma <- 1
mu <- 0

x <- Sym("x")
f <- 1/sqrt(2*pi*sigma^2)*exp(-(x-mu)^2/(2*sigma^2))
#print(f)
dx <- eval(deriv(g(x),Sym("x"))); #Derivative of f in terms of x
print(dx)
dxSimp <- Ryacas::Simplify(deriv(g(x),"x")) #Simplified version of derivative (collapse terms)...
print(dxSimp)

s = deriv(~a^2,'a',func = T) #Create function s(a)=a^2
#s(5) #5^2
```

```{r}
#Initial function (main)
Initial <- function(k_start,x.Bound,g,QC=FALSE){
  #print(all.equal(x.Bound,c(-Inf,Inf)))

    upBd <- x.Bound[length(x.Bound)]
    lowBd <- x.Bound[1]
    if (lowBd != -Inf){
      needPosHprime <- FALSE
    } else{
      needPosHprime <- TRUE
    }
    if (upBd != Inf){
      needNegHprime <- FALSE
    } else{
      needNegHprime <- TRUE
    }
    upBdInit <- upBd #Upper bound for initialization points
    lowBdInit <- lowBd #Lower bound for initialization points
    if (0==1){
      
      if (QC==TRUE){
        print("Lower & upper bound pairs")
        print(lowBd)
        print(upBd)
        
        print(upBdInit)
        print(lowBdInit)
      }
    }
    
    
    k <- 0
    X <- c()
    
    
    #print(paste0("Begin: Find initialization points"))
    while (k < k_start){
      samp <- rtruncnorm(1,a=lowBdInit,b=upBdInit)
      hPrime <- h_d(samp)
      if (QC==TRUE){
        print(paste0("Initialization bounds: ",lowBdInit," ",upBdInit))
        print(paste0("Need positive / negative h'? ",needPosHprime," ",needNegHprime))
          
        print(paste0("Sampled point x: ",samp))
        print(paste0("h'(x): ",h_d(samp)))
      }
      
      if (hPrime >0 & needPosHprime==TRUE){
        needPosHprime <- FALSE
        X <- append(X,samp,length(X))
        k <- k+1
        #print(paste0("Appended X with h'(X) > 0"))
        
        if (needNegHprime==TRUE) {
          lowBdInit <- samp
          #print(paste0("Changed lower initialization bound to sampled point"))
        }
        else {
          lowBdInit <- lowBd
          #print(paste0("Changed lower initialization bound to distribution lower bound"))
        }
      }
      else if (hPrime < 0 & needNegHprime==TRUE) {
        needNegHprime <- FALSE
        X <- append(X,samp,0)
        k <- k+1
        #print(paste0("Appended X with h'(X) < 0"))
        
        if (needPosHprime == TRUE) {
          upBdInit <- samp
          #print(paste0("Changed upper initialization bound to sampled point"))
        }
        else {
          upBdInit <- upBd
          #print(paste0("Changed upper initialization bound to distribution upper bound"))
        }
      }
      else if (k < (k_start-needPosHprime-needNegHprime)){
        X <- append(X,samp,length(X[X<samp]))
        k <- k+1
        #print(paste0("Appended X; no h' requirements met"))
      }
      else {
        #print(paste0("Sampled point does not satisfy any initialization requirements. Sample again."))
      }
    }
    #print(paste0("Finished: Find initialization points"))
    
    X <<- X
    H <<- h(X)
    H_d <<- h_d(X)
    Z <<- c(lowBd,upBd)
    lower <<- x.Bound[1]
    upper <<- x.Bound[2]
  #return(list(X,H,H_d,Z))
  #print(paste0("X is: ", X))
}
```


```{r}
g <- function(x){
  sigma <- 1
  mu <- 0
  val <- 3/sqrt(2*pi*sigma^2)*exp(-(x-mu)^2/(2*sigma^2))
}

Initial(k_start=10,x.Bound=c(-Inf,Inf),g
        #,QC=TRUE
        )

if (lower == -Inf) {
  testthat::expect_gt(H_d[1],0)
}

if (upper == Inf) {
  testthat::expect_lt(H_d[1],0)
}

```

```{r}
#Exponential distribution (10 starting pts)
  #User supplied g-function
g <- function(x){
  lam <- 1
  value <- lam*exp(-lam*x)
}
#a <- AbscontDistribution(d=g,low=0,low1=0)
#print(g(1))
Initial(k_start=2,x.Bound=c(0,Inf),g
        #,QC=TRUE
        )

if (lower == -Inf) {
  testthat::expect_gt(H_d[1],0)
}

if (upper == Inf) {
  testthat::expect_lt(H_d[1],0)
}

```

```{r}
g <- function(x){
  alpha <- 1
  beta <- 3
  val <- x^(alpha-1)*(1-x)^(beta-1)/(gamma(alpha)*gamma(beta)/gamma(alpha+beta))
}

Initial(k_start=10,x.Bound=c(0,Inf),g
        #,QC=TRUE
        )

if (lower == -Inf) {
  testthat::expect_gt(H_d[1],0)
}

if (upper == Inf) {
  testthat::expect_lt(H_d[1],0)
}
```

