---
title: "Update_accept"
author: "Anh Mai Bui"
date: "November 26, 2018"
output: pdf_document
---

```{r}
#Inputs
g <- function(x) {
  (3/sqrt(2*pi))*exp(-(x^2)/2)
}
X <- c(-1.7,1.5)
X <- sort(X)
x_star <- runif(1,min = X[1], max = X[2])

x_accept <- c()
length_accept <- 1
```

```{r}

update_accept <- function(x_star, g, X) {
  library(Deriv)
  g_prime <- Deriv(g)
  
  update_H <- function(x) {log(g(x))}
  update_H_prime <- function(x) {g_prime(x)/g(x)}
  
  l <- function(x,i) {
  ((X[i+1]-x)*H[i] + (x-X[i])*H[i+1])/(X[i+1]-X[i])
  }
  u <- function(x,i) {H[i] + (x-X[i])*H_prime[i]}
  
  H <- sapply(X, update_H)
  H_prime <- sapply(X, update_H_prime) 
  z <- function(i) {
  (H[i+1]-H[i]-X[i+1]*H_prime[i+1]+X[i]*H_prime[i])/(H_prime[i]-H_prime[i+1])
  }
  
  Z <- c()
  for (z_order in 1:length(X)-1) {
      Z[z_order] <- z(z_order)
    }
 
  w <- runif(1)
  
  i_star_x <- which.max(X[X<x_star])
  if(x_star<max(Z)){ 
    i_star_z <- which.min(Z[x_star<Z])
  }else { 
   i_star_z <- length(X)
  }
  
  if(w < exp(l(x_star,i_star_x) - u(x_star,i_star_z))){
    x_accept[length_accept] <<- x_star
    length_accept <<- length_accept+1
    print(paste0("No update. New x_accept"))

}else {
    #Update step
    X <- c(X, x_star)
    X <- sort(X)
    H <- sapply(X, update_H)
    H_prime <- sapply(X, update_H_prime)
    for (z_order in 1:length(X)-1) {
      Z[z_order] <- z(z_order)}
    X <<- X
    H <<- H
    H_prime <<- H_prime 
    Z <<- Z
    print(paste0("Abscissae is updated"))
    print(paste0("New H is updated"))
    print(paste0("New H_prime is updated"))
    
    if (w < exp(log(g(x_star)) - u(x_star,i_star_z))) {
    x_accept[length_accept] <<- x_star
    length_accept <<- length_accept+1
    print(paste0("Update step is done. New x_accept"))
    }
      }
}

#update_accept(0.2,g,X)
```



